### ISSUE TITLE
poi depency upgrade to 5.0.0 leads to ClassNotFoundException

### ISSUE THREAD

**Issue by ake2l** [rapiddweller/rapiddweller-benerator-ce#23]
The execution of XLS and XLSX dependend demo testcases run into ClassNotFoundException

```java
Caused by: java.lang.ClassNotFoundException: org.apache.commons.math3.util.ArithmeticUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 8 more
```

**Comment by ake2l** [comment]
It seems like because of changes in the depency structure during migration from poi 3.x to 5.0.0, the related Class is not part of poi packages anymore. I added following dependency to assebly process

`<include>org.apache.commons:commons-math3:jar</include>`

test looks good
