### ISSUE TITLE
benerator-wizard database project SQL type not mapped

### ISSUE THREAD

**Issue by ghost** [rapiddweller/rapiddweller-benerator-ce#379]
**Describe the bug**
Using the Benerator wizard on a postgreSQL database with tables using a column with a text[] type the project generation failes.

**To Reproduce**
1. create a postgreSQL database with a table using text[] in a column
  create table exampletable;
  alter table exampletable add columntests text[];
3. Start the benerator-wizard 
4. set up the database conection 
5. click 'Anlegen'

**Expected behavior**
The project should be set up properly.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/67778897/227568902-1cd983a1-f257-43be-8b64-b66efae89064.png)

`Error: Error processing column metering_device_types of table consumer_unit_avg_consumption
        at com.rapiddweller.common.exception.ExceptionFactory.configurationError(ExceptionFactory.java:151)
        at com.rapiddweller.platform.db.AbstractDBSystem.mapTableToComplexTypeDescriptor(AbstractDBSystem.java:898)
        at com.rapiddweller.platform.db.LazyTableComplexTypeDescriptor.assureLoaded(LazyTableComplexTypeDescriptor.java:73)
        at com.rapiddweller.platform.db.LazyTableComplexTypeDescriptor.getComponents(LazyTableComplexTypeDescriptor.java:91)
        at com.rapiddweller.model.data.DataModel.validate(DataModel.java:173)
        at com.rapiddweller.model.data.DataModel.validate(DataModel.java:155)
        at com.rapiddweller.model.data.DataModel.validate(DataModel.java:145)
        at com.rapiddweller.model.data.DataModel.addDescriptorProvider(DataModel.java:80)
        at com.rapiddweller.model.data.DataModel.addDescriptorProvider(DataModel.java:73)
        at com.rapiddweller.benerator.gui.ProjectBuilder.getDBSystem(ProjectBuilder.java:557)
        at com.rapiddweller.benerator.gui.ProjectBuilder.parseDatabaseMetaData(ProjectBuilder.java:308)
        at com.rapiddweller.benerator.gui.ProjectBuilder.run(ProjectBuilder.java:250)
        at com.rapiddweller.benerator.gui.CreateProjectPanel$Creator.run(CreateProjectPanel.java:356)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at com.rapiddweller.model.data.DataModel.addDescriptorProvider(DataModel.java:80)
        at com.rapiddweller.model.data.DataModel.addDescriptorProvider(DataModel.java:73)
        at com.rapiddweller.benerator.gui.ProjectBuilder.getDBSystem(ProjectBuilder.java:557)
        at com.rapiddweller.benerator.gui.ProjectBuilder.parseDatabaseMetaData(ProjectBuilder.java:308)
        at com.rapiddweller.benerator.gui.ProjectBuilder.run(ProjectBuilder.java:250)
        at com.rapiddweller.benerator.gui.CreateProjectPanel$Creator.run(CreateProjectPanel.java:356)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: Error: Platform specific SQL type (2003) not mapped: _TEXT
        at com.rapiddweller.common.exception.ExceptionFactory.configurationError(ExceptionFactory.java:151)
        at com.rapiddweller.common.exception.ExceptionFactory.configurationError(ExceptionFactory.java:147)
        at com.rapiddweller.platform.db.JdbcMetaTypeMapper.abstractType(JdbcMetaTypeMapper.java:101)
        at com.rapiddweller.platform.db.AbstractDBSystem.mapTableToComplexTypeDescriptor(AbstractDBSystem.java:860)
        ... 12 more
`

**Desktop (please complete the following information):**
Benerator Community Edition 3.1.0-jdk-11 build 2023-02-15 14:10:47
Java version:  17.0.5
JVM product:   OpenJDK 64-Bit Server VM 17.0.5+8-LTS (Amazon.com Inc.)
System:        Windows 10 10.0 amd64
CPU & RAM:     8 cores and 31 GB RAM, max 7 GB of RAM for this process

**Comment by ake2l** [comment]
Hi Niels, would you please add an example SQL script thanks.

**Comment by ghost** [comment]
An example script (it seems you have found one too) would be:

```
CREATE TABLE sal_emp (
    name            text,
    pay_by_quarter  integer[],
    schedule        text[][]
);
```
from: 
https://www.postgresql.org/docs/current/arrays.html

**Comment by ake2l** [comment]
Hi Niels,

I wanted to let you know that the enhancement of our community edition has been realized! We've made changes to ensure that all PostgreSQL data types are now supported, and these changes have been merged into the actual dev branch.

Please check if this is working for you.

here we have a demo now, with all supported postgresql types

https://github.com/rapiddweller/rapiddweller-benerator-ce/blob/development/src/demo/resources/demo/db/postgresalltypes.ben.xml


Thank you for your patience while we worked on this. We hope that this update will make your experience with our community edition even better. Let us know if you have any questions or feedback.

**Comment by ake2l** [comment]
Hi @NielsFeldtmannKALO , you reopended this ticket, is there still an issue with the existing implementation? Could you provide us more informations or in case everything looks good for now, please close the ticket

**Comment by ghost** [comment]
I haven't finally tested the new code; using the benerator-wizard command I cannot select db scripts.
Should I file a new Issue?

![grafik](https://user-images.githubusercontent.com/67778897/235607229-4eaba25a-145a-4054-a1ed-40359be27f7f.png)

**Comment by ake2l** [comment]
Hi Niels,

I wanted to let you know that we no longer support the wizard options you mentioned. We've found that the create table and drop table scripts, as well as Snapshot increase complexity and create maintenance issues for us in the Community Edition version of our software.

While the current version of the wizard is intended to provide a simple reliable quickstart with low complexity. As a result, we're planning to reduce the functionality of the wizard more and more over time to ensure that the existing options are working as expected and are actually providing value to our users.
 
If you have any further questions or concerns, please let us know.

**Comment by ake2l** [comment]
in case there are still issues please reopen , should be fixed
