### ISSUE TITLE
Improve compatibility of benerator with Vertica

### ISSUE THREAD

**Issue by ake2l** [rapiddweller/rapiddweller-benerator-ce#394]
Currently, Benerator does not provide seamless integration with Vertica database systems. This issue aims to address this limitation and improve Benerator's compatibility with Vertica.

In order to achieve this goal, we have gathered crucial information on SQL command limitations, data type mapping, system tables, and system limits related to objects for these database systems. We are in the process of reviewing this information and welcome any further suggestions or requirements to enhance compatibility.

SQL Command Limitations:
A comparison of SQL command limitations between Vertica and PostgreSQL or Oracle databases is needed to understand and address the compatibility issues. The complete [SQL reference](https://docs.vertica.com/12.0.x/en/sql-reference/) and a guide highlighting [differences between PostgreSQL and vSQL](https://docs.vertica.com/12.0.x/en/extending/stored-procedures/plvsql/plpgsql-to-plvsql-migration/).

Data Type Mapping:
To ensure seamless integration, we require a comprehensive list of data type mappings between Oracle and Vertica. (vSQL) Here is a list of [SQL data type mapping between Oracle and Vertica](https://docs.vertica.com/12.0.x/en/sql-reference/data-types/data-type-mappings-between-and-oracle/)

System Tables:
Please provide information on the available system tables and their structure, specifically focusing on the V_Catalog schema, which offers metadata information about persistent objects in the Catalog.[here](https://docs.vertica.com/12.0.x/en/admin/monitoring/using-system-tables/) is the link to it. In which the [V_Catalog schema](https://docs.vertica.com/12.0.x/en/sql-reference/system-tables/v-catalog-schema/) provides metadata information about persistent objects in the Catalog, that link has all the table structures.

Restrictions and Limitations:
A list of any other restrictions or limitations that may apply to Vertica systems should be included to help identify and address potential compatibility issues. Here is a list of [system limits](https://docs.vertica.com/12.0.x/en/sql-reference/system-limits/) in terms of objects in Vertica DB.

We appreciate your input and assistance as we work to improve Benerator's compatibility with Vertica database systems

**Comment by ake2l** [comment]
waiting for test system

**Comment by ake2l** [comment]
Following image can be used as Testsystem

https://hub.docker.com/r/vertica/vertica-ce

**Comment by ake2l** [comment]
A quick intro, Vertica by Open Text (https://www.vertica.com/) is an advanced analytics database management software based on a massively scalable architecture. We are trying to generate “near real” data for a use-case and that is how we came across Benerator (although Mark W in cc has used it a few times earlier as well with other DBs), and although it works perfectly fine with Postgres it unfortunately is not working with Vertica. We understand that Vertica is not in the list of “supported” databases but since it is JDBC compliant we thought it was worth a try. I have given the error and other details below and was hoping if you could point us in the right direction.
 

$ benerator --version

Benerator Community Edition 3.2.0-jdk-11-SNAPSHOT build 2023-04-14 05:29:11

Java version:  11.0.18

JVM product:   OpenJDK 64-Bit Server VM 11.0.18+10-LTS (Red Hat, Inc.)

System:        Linux 3.10.0-1160.25.1.el7.x86_64 amd64

CPU & RAM:     40 cores and 125 GB RAM, max 29 GB of RAM for this process

 

$ mvn -version

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

Maven home: /usr/local/apache-maven/apache-maven-3.9.1/apache-maven-3.9.1

Java version: 11.0.18, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.18.0.10-1.el7_9.x86_64

Default locale: en_GB, platform encoding: UTF-8

OS name: "linux", version: "3.10.0-1160.25.1.el7.x86_64", arch: "amd64", family: "unix"

 

 

[INFO ] 2023-04-14 08:44:04.627 [main] Benerator - benerator flight_generator_rapiddweller.xml

[INFO ] 2023-04-14 08:44:04.772 [main] Benerator - ------------------------------------------------------------------------------------------------------------------------

[INFO ] 2023-04-14 08:44:04.775 [main] CONFIG - Running file flight_generator_rapiddweller.xml

[INFO ] 2023-04-14 08:44:04.831 [main] CONFIG - Benerator Community Edition 3.2.0-jdk-11-SNAPSHOT build 2023-04-14 05:29:11

[INFO ] 2023-04-14 08:44:04.831 [main] CONFIG - Mode:          lenient

[INFO ] 2023-04-14 08:44:04.831 [main] CONFIG - Java version:  11.0.18

[INFO ] 2023-04-14 08:44:04.832 [main] CONFIG - JVM product:   OpenJDK 64-Bit Server VM 11.0.18+10-LTS (Red Hat, Inc.)

[INFO ] 2023-04-14 08:44:04.832 [main] CONFIG - System:        Linux 3.10.0-1160.25.1.el7.x86_64 amd64

[INFO ] 2023-04-14 08:44:04.832 [main] CONFIG - CPU & RAM:     40 cores and 125 GB RAM, max 29 GB of RAM for this process

[INFO ] 2023-04-14 08:44:04.832 [main] CONFIG - Slf4j is configured to use Log4j

[INFO ] 2023-04-14 08:44:04.874 [main] CONFIG - Log4j is configured properly

[INFO ] 2023-04-14 08:44:04.881 [main] CONFIG - Configured heap size limit: 30688 MB

[INFO ] 2023-04-14 08:44:05.922 [main] Importer - Imported platforms: csv, db, dbunit, fixedwidth, memstore, result, template, xls, xml, mongodb

[INFO ] 2023-04-14 08:44:06.109 [main] JDBC - Connected to Vertica Database 11.00.0200

[INFO ] 2023-04-14 08:44:06.109 [main] JDBC - Using driver vertica.jar 11.00.0200

[INFO ] 2023-04-14 08:44:06.109 [main] JDBC - JDBC version 4.2

[INFO ] 2023-04-14 08:44:06.182 [main] JDBCDBImporter - Importing tables from environment 'null'

[INFO ] 2023-04-14 08:44:06.209 [main] DefaultDBSystem - Fetching table details and ordering tables by dependency

[ERROR] 2023-04-14 08:44:06.306 [main] Benerator - Error in Benerator execution

com.rapiddweller.common.exception.DBQueryFailed: Error in database query: 'SELECT 1 from dual;': [Vertica][JDBC](10220) Driver does not support this optional feature.

        at com.rapiddweller.benerator.factory.BeneratorExceptionFactory.dbQueryFailed(BeneratorExceptionFactory.java:192) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.jdbacl.QueryDataIterator.handleException(QueryDataIterator.java:70) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.jdbacl.QueryDataIterator.createSource(QueryDataIterator.java:57) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.jdbacl.QueryDataIterator.<init>(QueryDataIterator.java:45) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.platform.db.QueryDataSource.iterator(QueryDataSource.java:98) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.format.util.ConvertingDataSource.iterator(ConvertingDataSource.java:59) ~[rd-lib-format-1.1.6-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.wrapper.DataSourceGenerator.generate(DataSourceGenerator.java:107) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.util.GeneratorUtil.allProducts(GeneratorUtil.java:107) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.distribution.IndexBasedSampleGeneratorProxy.initMembers(IndexBasedSampleGeneratorProxy.java:92) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.distribution.IndexBasedSampleGeneratorProxy.init(IndexBasedSampleGeneratorProxy.java:74) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.composite.SourcedGenerationStep.init(SourcedGenerationStep.java:60) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.statement.GenIterTask.initStatements(GenIterTask.java:302) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.statement.GenIterTask.init(GenIterTask.java:128) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.statement.GenIterStatement.beInitialized(GenIterStatement.java:230) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.statement.GenIterStatement.execute(GenIterStatement.java:154) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.statement.LazyStatement.execute(LazyStatement.java:63) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.statement.SequentialStatement.executeSubStatements(SequentialStatement.java:72) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.statement.SequentialStatement.execute(SequentialStatement.java:61) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.BeneratorRootStatement.execute(BeneratorRootStatement.java:65) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.DescriptorRunner.execute(DescriptorRunner.java:128) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.DescriptorRunner.runWithoutShutdownHook(DescriptorRunner.java:102) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.engine.DescriptorRunner.run(DescriptorRunner.java:94) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.main.Benerator.runFile(Benerator.java:261) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.main.Benerator.run(Benerator.java:192) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.main.Benerator.runWithArgs(Benerator.java:164) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.benerator.main.Benerator.main(Benerator.java:110) ~[rapiddweller-benerator-ce-3.2.0-jdk-11-SNAPSHOT.jar:?]

Caused by: com.rapiddweller.common.OperationFailed: Failed to invoke public abstract java.sql.Statement java.sql.Connection.createStatement(int,int,int) throws java.sql.SQLException

        at com.rapiddweller.common.exception.ExceptionFactory.operationFailed(ExceptionFactory.java:187) ~[rd-lib-common-2.0.0-jdk-11.jar:?]

        at com.rapiddweller.common.exception.ExceptionFactory.operationFailed(ExceptionFactory.java:183) ~[rd-lib-common-2.0.0-jdk-11.jar:?]

        at com.rapiddweller.common.BeanUtil.invoke(BeanUtil.java:734) ~[rd-lib-common-2.0.0-jdk-11.jar:?]

        at com.rapiddweller.common.BeanUtil.invoke(BeanUtil.java:677) ~[rd-lib-common-2.0.0-jdk-11.jar:?]

        at com.rapiddweller.jdbacl.proxy.PooledConnectionHandler.createStatement(PooledConnectionHandler.java:159) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.jdbacl.proxy.PooledConnectionHandler.invoke(PooledConnectionHandler.java:153) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        at com.sun.proxy.$Proxy26.createStatement(Unknown Source) ~[?:?]

        at com.rapiddweller.jdbacl.QueryDataIterator.createSource(QueryDataIterator.java:51) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        ... 23 more

Caused by: java.lang.reflect.InvocationTargetException

        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]

        at com.rapiddweller.common.BeanUtil.invoke(BeanUtil.java:732) ~[rd-lib-common-2.0.0-jdk-11.jar:?]

        at com.rapiddweller.common.BeanUtil.invoke(BeanUtil.java:677) ~[rd-lib-common-2.0.0-jdk-11.jar:?]

        at com.rapiddweller.jdbacl.proxy.PooledConnectionHandler.createStatement(PooledConnectionHandler.java:159) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.jdbacl.proxy.PooledConnectionHandler.invoke(PooledConnectionHandler.java:153) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        at com.sun.proxy.$Proxy26.createStatement(Unknown Source) ~[?:?]

        at com.rapiddweller.jdbacl.QueryDataIterator.createSource(QueryDataIterator.java:51) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        ... 23 more

Caused by: java.sql.SQLFeatureNotSupportedException: [Vertica][JDBC](10220) Driver does not support this optional feature.

        at com.vertica.exceptions.ExceptionConverter.toSQLException(ExceptionConverter.java:136) ~[vertica-jdbc-11.0.2-0.jar:?]

        at com.vertica.jdbc.common.SConnection.createStatement(SConnection.java:578) ~[vertica-jdbc-11.0.2-0.jar:?]

        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]

        at com.rapiddweller.common.BeanUtil.invoke(BeanUtil.java:732) ~[rd-lib-common-2.0.0-jdk-11.jar:?]

        at com.rapiddweller.common.BeanUtil.invoke(BeanUtil.java:677) ~[rd-lib-common-2.0.0-jdk-11.jar:?]

        at com.rapiddweller.jdbacl.proxy.PooledConnectionHandler.createStatement(PooledConnectionHandler.java:159) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        at com.rapiddweller.jdbacl.proxy.PooledConnectionHandler.invoke(PooledConnectionHandler.java:153) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        at com.sun.proxy.$Proxy26.createStatement(Unknown Source) ~[?:?]

        at com.rapiddweller.jdbacl.QueryDataIterator.createSource(QueryDataIterator.java:51) ~[rd-lib-jdbacl-1.1.15-jdk-11-SNAPSHOT.jar:?]

        ... 23 more

[ERROR] 2023-04-14 08:44:06.325 [main] Benerator - Error BEN-1101: Error in database query: 'SELECT 1 from dual;': [Vertica][JDBC](10220) Driver does not support this optional feature.

**Comment by ake2l** [comment]
fixed
