### ISSUE TITLE
Error when generating using MySQL driver

### ISSUE THREAD

**Issue by tglanz** [rapiddweller/rapiddweller-benerator-ce#56]
**Describe the bug**
Trying to generate a very simple data using MySQL driver (MariaDB instance though).

Getting the following error:
```
java.lang.RuntimeException: Database import failed for environment ___temp
	at com.rapiddweller.jdbacl.model.Database.<init>(Database.java:128) ~[rd-lib-jdbacl-1.1.7-jdk-11.jar:?]
	at com.rapiddweller.jdbacl.model.jdbc.JDBCDBImporter.importDatabase(JDBCDBImporter.java:311) ~[rd-lib-jdbacl-1.1.7-jdk-11.jar:?]
	at com.rapiddweller.platform.db.DBSystem.fetchDbMetaData(DBSystem.java:981) ~[classes/:?]
	at com.rapiddweller.platform.db.DBSystem.getDbMetaData(DBSystem.java:947) ~[classes/:?]
	at com.rapiddweller.platform.db.DBSystem.parseMetaData(DBSystem.java:891) ~[classes/:?]
	at com.rapiddweller.platform.db.DBSystem.parseMetadataIfNecessary(DBSystem.java:1373) ~[classes/:?]
	at com.rapiddweller.platform.db.DBSystem.getTypeDescriptor(DBSystem.java:569) ~[classes/:?]
	at com.rapiddweller.model.data.DataModel.getTypeDescriptor(DataModel.java:172) ~[classes/:?]
	at com.rapiddweller.model.data.DataModel.getTypeDescriptor(DataModel.java:142) ~[classes/:?]
	at com.rapiddweller.benerator.engine.parser.xml.GenerateOrIterateParser.mapDescriptorElement(GenerateOrIterateParser.java:192) ~[classes/:?]
	at com.rapiddweller.benerator.engine.parser.xml.GenerateOrIterateParser.parseGenerate(GenerateOrIterateParser.java:265) ~[classes/:?]
	at com.rapiddweller.benerator.engine.parser.xml.GenerateOrIterateParser$1.evaluate(GenerateOrIterateParser.java:236) ~[classes/:?]
	at com.rapiddweller.benerator.engine.parser.xml.GenerateOrIterateParser$1.evaluate(GenerateOrIterateParser.java:233) ~[classes/:?]
	at com.rapiddweller.benerator.engine.statement.LazyStatement.getRealStatement(LazyStatement.java:68) ~[classes/:?]
	at com.rapiddweller.benerator.engine.statement.LazyStatement.execute(LazyStatement.java:75) ~[classes/:?]
	at com.rapiddweller.benerator.engine.statement.StatementProxy.execute(StatementProxy.java:60) ~[classes/:?]
	at com.rapiddweller.benerator.engine.statement.TimedGeneratorStatement.execute(TimedGeneratorStatement.java:81) ~[classes/:?]
	at com.rapiddweller.benerator.engine.statement.SequentialStatement.executeSubStatements(SequentialStatement.java:72) ~[classes/:?]
	at com.rapiddweller.benerator.engine.statement.SequentialStatement.execute(SequentialStatement.java:61) ~[classes/:?]
	at com.rapiddweller.benerator.engine.BeneratorRootStatement.execute(BeneratorRootStatement.java:72) ~[classes/:?]
	at com.rapiddweller.benerator.engine.DescriptorRunner.execute(DescriptorRunner.java:171) [classes/:?]
	at com.rapiddweller.benerator.engine.DescriptorRunner.runWithoutShutdownHook(DescriptorRunner.java:142) [classes/:?]
	at com.rapiddweller.benerator.engine.DescriptorRunner.run(DescriptorRunner.java:130) [classes/:?]
	at com.rapiddweller.benerator.main.Benerator.runFile(Benerator.java:113) [classes/:?]
	at com.rapiddweller.benerator.main.Benerator.runFromCommandLine(Benerator.java:87) [classes/:?]
	at com.rapiddweller.benerator.main.Benerator.main(Benerator.java:79) [classes/:?]
Caused by: java.sql.SQLException: Table not specified.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.DatabaseMetaData.getImportedKeys(DatabaseMetaData.java:2612) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.rapiddweller.jdbacl.model.jdbc.JDBCDBImporter.getForeignSchemas(JDBCDBImporter.java:409) ~[rd-lib-jdbacl-1.1.7-jdk-11.jar:?]
	at com.rapiddweller.jdbacl.model.jdbc.JDBCDBImporter.importSchemas(JDBCDBImporter.java:429) ~[rd-lib-jdbacl-1.1.7-jdk-11.jar:?]
	at com.rapiddweller.jdbacl.model.Database.<init>(Database.java:124) ~[rd-lib-jdbacl-1.1.7-jdk-11.jar:?]
	... 25 more
[INFO ] 2021-07-21 20:04:33.870 [main] CONFIG - Max. committed heap size: 248 MB

Process finished with exit code 0
```

**To Reproduce**

using the benerator file (database.env.properties aside)
```xml
<?xml version="1.0" encoding="utf-8"?>
<setup
    xmlns="[https://www.benerator.de/schema/1.0.0](https://www.benerator.de/schema/1.0.0)"
    xmlns:xsi="[http://www.w3.org/2001/XMLSchema-instance](http://www.w3.org/2001/XMLSchema-instance)"
    xsi:schemaLocation="https://www.benerator.de/schema/1.0.0 https://www.benerator.de/schema/rapiddweller-benerator-ce-1.0.0.xsd">

    <import platforms="db" />
    <database id="database" environment="database" /> 
    <generate type="sample" count="1" consumer="database" />
</setup>
```

and the schema
```sql
create table sample (
  id int primary key
);
```

and executing ```benerator```

**Expected behavior**
have a generated row in the target database

**Additional context**
Have encountered this issue both in the head and the latest release.

after investigating a bit, the issue arising in [Database.java](https://github.com/rapiddweller/rd-lib-jdbacl/blob/816e3ad60415d196e2b5c7d7da3db6cad503a0a8/src/main/java/com/rapiddweller/jdbacl/model/Database.java#L124) which evantually reaches [JDBCImporter#getForeignSchemas](https://github.com/rapiddweller/rd-lib-jdbacl/blob/816e3ad60415d196e2b5c7d7da3db6cad503a0a8/src/main/java/com/rapiddweller/jdbacl/model/jdbc/JDBCDBImporter.java#L440) which practically passes ```table = null``` to MySQL's [DatabaseMetaData#getImportedKeys](https://github.com/mysql/mysql-connector-j/blob/4f7120a617b9d5efb9dedda9064b9896db424a60/src/main/user-impl/java/com/mysql/cj/jdbc/DatabaseMetaData.java#L2628) that throws the exception when the table argument is null.

Hope I haven't misguided anything, but is MySQL even supported?

**Comment by ake2l** [comment]
Actually, Mysql DB is supported.
You might want to check [this](https://github.com/rapiddweller/rapiddweller-benerator-ce/runs/3100659755?check_suite_focus=true) for example or [this](https://github.com/rapiddweller/rapiddweller-benerator-ce/blob/development/src/demo/resources/demo/shop/shop-mysql.ben.xml). 
These examples are also part of the integration test and e2et. 
Would you please share your database.env.properties file, I would like to check what is wrong with your case.

**Comment by ake2l** [comment]
I just checked your case

```xml
<?xml version="1.0" encoding="utf-8"?>
<setup>

    <import platforms="db"/>
    <database id="database" environment="database"/>
    <execute type="sql" target="database">
        create table sample (
        id int primary key
        );
    </execute>
    <generate type="sample" count="1" consumer="database"/>
</setup>
```

i placed this database.env.properties into $HOME/rapiddweller/

```
db_url=jdbc:mysql://localhost:33306/benerator
db_driver=com.mysql.cj.jdbc.Driver
db_user=root
db_password=benerator
```
for me, it is working fine

**Comment by tglanz** [comment]
Thank you!
