### ISSUE TITLE
echo statement encloses automatically on line break

### ISSUE THREAD

**Issue by PeterBrinkhoff** [rapiddweller/rapiddweller-benerator-ce#58]
**Describe the bug**
If you use an <echo/> node to print information in combination with freemarker templates e.g. to print the whole object for debugging, a line break is enclosing the script. 

**To Reproduce**
1. Execute the following benerator script:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<setup defaultPageSize="100" defaultSeparator="|">
  <import domains="person, us"/>
  <generate type="test_entity" count="10" >
    <variable name="person" generator="new PersonGenerator{dataset='US',locale='de',minAgeYears='21', maxAgeYears='67',femaleQuota='0.5'}"/>
      <echo>{ftl:${person}}
      </echo>
  </generate>
</setup>
``` 
2. Note the new line between `{ftl:${person}}` and `</echo>`

**Expected behavior**
Echo information is printed in the console (or any other consumer) without an additional curly bracket `}`. 

**Log Output**
```
[WARN ] 2021-08-13 11:53:37.419 [main] XMLConsumerExpression - XMLConsumerExpression(<generate count="10" type="test_entity"...): No consumers defined for null
[INFO ] 2021-08-13 11:53:37.478 [main] TaskExecutor - Running task StateTrackingTaskProxy[GenerateAndConsumeTask(test_entity)] 10 times with page size 100 in a single thread
Herr Thomas Keith}
Herr Dr. Rodney Castro}
Herr William Holt}
Frau Barbara Moore}
Herr Wesley Brown}
Frau Melinda Smith}
Herr John Hughes}
Herr Warren Smith}
Frau Dianne Mason}
Frau Herminia White}
```

**Desktop (please complete the following information):**
 - OS: reproduced on Mac, Ubuntu
 - Version 1.1.1

**Additional context**
- If there is no linebreak after the enclosing curly bracket, everything works fine. 
- 1..n spaces/line breaks before the `{ftl:` block starts, also break benerator with below exception. Trimming of spaces or line breaks would be appreciated. 

Error Log:
```
[ERROR] 2021-08-13 12:01:11.457 [main] DescriptorRunner - Error in Benerator execution
com.rapiddweller.common.SyntaxError: Error parsing Benerator Script expression
	at com.rapiddweller.script.DatabeneScriptParser.mapToSyntaxError(DatabeneScriptParser.java:237) ~[rd-lib-script-1.1.1-jdk-11.jar:?]
	at com.rapiddweller.script.DatabeneScriptParser.parseExpression(DatabeneScriptParser.java:92) ~[rd-lib-script-1.1.1-jdk-11.jar:?]
	at com.rapiddweller.benerator.script.BeneratorScriptFactory.parseText(BeneratorScriptFactory.java:49) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.format.script.ScriptUtil.parseScriptText(ScriptUtil.java:211) ~[rd-lib-format-1.1.2-jdk-11.jar:?]
	at com.rapiddweller.format.script.ScriptUtil.parseScriptText(ScriptUtil.java:194) ~[rd-lib-format-1.1.2-jdk-11.jar:?]
	at com.rapiddweller.format.script.ScriptUtil.parseUnspecificText(ScriptUtil.java:145) ~[rd-lib-format-1.1.2-jdk-11.jar:?]
	at com.rapiddweller.format.script.ScriptUtil.evaluate(ScriptUtil.java:108) ~[rd-lib-format-1.1.2-jdk-11.jar:?]
	at com.rapiddweller.benerator.engine.expression.ScriptableExpression.evaluate(ScriptableExpression.java:82) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.script.expression.StringExpression.evaluate(StringExpression.java:39) ~[rd-lib-script-1.1.1-jdk-11.jar:?]
	at com.rapiddweller.script.expression.StringExpression.evaluate(StringExpression.java:28) ~[rd-lib-script-1.1.1-jdk-11.jar:?]
	at com.rapiddweller.script.expression.ExpressionProxy.evaluate(ExpressionProxy.java:34) ~[rd-lib-script-1.1.1-jdk-11.jar:?]
	at com.rapiddweller.script.expression.UnescapeExpression.evaluate(UnescapeExpression.java:35) ~[rd-lib-script-1.1.1-jdk-11.jar:?]
	at com.rapiddweller.script.expression.UnescapeExpression.evaluate(UnescapeExpression.java:27) ~[rd-lib-script-1.1.1-jdk-11.jar:?]
	at com.rapiddweller.script.expression.ExpressionUtil.evaluate(ExpressionUtil.java:54) ~[rd-lib-script-1.1.1-jdk-11.jar:?]
	at com.rapiddweller.benerator.engine.statement.EchoStatement.execute(EchoStatement.java:70) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.benerator.engine.statement.GenerateAndConsumeTask.execute(GenerateAndConsumeTask.java:211) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.task.TaskProxy.execute(TaskProxy.java:81) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.task.StateTrackingTaskProxy.execute(StateTrackingTaskProxy.java:73) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.task.TaskExecutor.runWithoutPage(TaskExecutor.java:104) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.task.TaskExecutor.runPage(TaskExecutor.java:219) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.task.TaskExecutor.run(TaskExecutor.java:181) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.task.TaskExecutor.run(TaskExecutor.java:150) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.task.TaskExecutor.execute(TaskExecutor.java:96) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.benerator.engine.statement.GenerateOrIterateStatement.executeTask(GenerateOrIterateStatement.java:249) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.benerator.engine.statement.GenerateOrIterateStatement.execute(GenerateOrIterateStatement.java:163) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.benerator.engine.statement.LazyStatement.execute(LazyStatement.java:75) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
	at com.rapiddweller.benerator.engine.statement.StatementProxy.execute(StatementProxy.java:60) ~[rapiddweller-benerator-ce-1.1.3-jdk-11-SNAPSHOT.jar:?]
```

**Comment by ake2l** [comment]
already fixed in actual dev branch
