### ISSUE TITLE
Add support for Azure SQL

### ISSUE THREAD

**Issue by JustinH-EY** [rapiddweller/rapiddweller-benerator-ce#60]
**Describe the bug**
Azure SQL does not support the USE statement so many Benerator functions do not work

**To Reproduce**
1. Launch wizard
2. Choose "Create DB Snapshot"
3. Enter Azure SQL url and other required info for SQL connection in Wizard
3. Test connection (successful)
4. Click "Create"
5. See stack trace reporting USE statement is not supported

**Expected behavior**
Should successful perform operations, even if it's a different approach for Azure SQL

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome, safari]: NA
 - Version [e.g. 22] Latest release

**Comment by ake2l** [comment]
Can you post your stack trace and describe the steps between 3 and 4 in a bit more detail.
I just did a rough check, the M SQL Server and Azure SQL are pretty much similar when it comes to compatibility and they are using the same JDBC driver. 
In the worst case, there are differences in detail, so this would mean an Azure-SQL DB dialect would be needed.

**Comment by JustinH-EY** [comment]
**edit: clarified steps in original issue**

Agree it's the same driver, just Azure SQL does not support USE statement that Benerator uses for the "Create DB Snapshot" process

> In Azure SQL Database, the database parameter can only refer to the current database. If a database other than the current database is provided, the USE statement does not switch between databases, and error code 40508 is returned. To change databases, you must directly connect to the database. 

https://docs.microsoft.com/en-us/sql/t-sql/language-elements/use-transact-sql?view=sql-server-ver15

Here's the stack trace
[INFO ] 2021-09-09 08:04:18.080 [Thread-0] CreateProjectPanel - Creating project test of type snapshotdb in
 
[INFO ] 2021-09-09 08:04:18.353 [Thread-0] JDBC - Connected to Microsoft SQL Server 12.00.2195

[INFO ] 2021-09-09 08:04:18.353 [Thread-0] JDBC - Using driver Microsoft JDBC Driver 9.2 for SQL Server 9.2.1.0

[INFO ] 2021-09-09 08:04:18.369 [Thread-0] JDBC - JDBC version 4.3

[INFO ] 2021-09-09 08:04:18.554 [Thread-0] JDBCDBImporter - Importing tables from environment '___temp'
java.lang.RuntimeException: Database import failed for environment ___temp
        at com.rapiddweller.jdbacl.model.Database.<init>(Database.java:128)
        at com.rapiddweller.jdbacl.model.jdbc.JDBCDBImporter.importDatabase(JDBCDBImporter.java:311)
        at com.rapiddweller.platform.db.DBSystem.fetchDbMetaData(DBSystem.java:986)
        at com.rapiddweller.platform.db.DBSystem.getDbMetaData(DBSystem.java:948)
        at com.rapiddweller.platform.db.DBSystem.parseMetaData(DBSystem.java:892)
        at com.rapiddweller.platform.db.DBSystem.parseMetadataIfNecessary(DBSystem.java:1375)
        at com.rapiddweller.platform.db.DBSystem.getTypeDescriptors(DBSystem.java:557)
        at com.rapiddweller.model.data.DataModel.validate(DataModel.java:194)
        at com.rapiddweller.model.data.DataModel.addDescriptorProvider(DataModel.java:102)
        at com.rapiddweller.model.data.DataModel.addDescriptorProvider(DataModel.java:88)
        at com.rapiddweller.benerator.gui.ProjectBuilder.getDBSystem(ProjectBuilder.java:545)
        at com.rapiddweller.benerator.gui.ProjectBuilder.parseDatabaseMetaData(ProjectBuilder.java:307)
        at com.rapiddweller.benerator.gui.ProjectBuilder.run(ProjectBuilder.java:254)
        at com.rapiddweller.benerator.gui.CreateProjectPanel$Creator.run(CreateProjectPanel.java:406)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: USE statement is not supported to switch between databases. Use a new connection to connect to a different database.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
        at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:3314)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3272)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:3318)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.setCatalog(SQLServerConnection.java:3670)
        at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.switchCatalogs(SQLServerDatabaseMetaData.java:390)
        at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getResultSetFromStoredProc(SQLServerDatabaseMetaData.java:344)
        at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getResultSetWithProvidedColumnNames(SQLServerDatabaseMetaData.java:366)
        at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getTables(SQLServerDatabaseMetaData.java:549)
        at com.rapiddweller.jdbacl.model.jdbc.JDBCDBImporter.importAllTables(JDBCDBImporter.java:486)
        at com.rapiddweller.jdbacl.model.jdbc.JDBCDBImporter.importSchemas(JDBCDBImporter.java:461)
        at com.rapiddweller.jdbacl.model.Database.<init>(Database.java:124)
        ... 14 more

**Comment by ake2l** [comment]
Alright, thanks for the more detailed clarification. Your actual Wizard Version was not touched in the last years, so the Wizard and DB Snapshot Tool were not reworked so far. In the new Version 1.2.0 what is just in preparation (you can check the  [Archetype Branch](https://github.com/rapiddweller/rapiddweller-benerator-ce/tree/archetypes) ), we reworked the wizard a bit to make sure all project options work out of the box. 
But we had to reduce the project type options to only these 

- hello
- simple
- csv
- db
- shopdb

The rework of the other project types and DBSnapshot tool is not in the scope of the community edition ( not in near future )

**Comment by JustinH-EY** [comment]
ah, ok. Perhaps the enhancement then is to some how make that clear in the wizard that certain functions are not available/aren't maintained/don't work (disable it, remove it, add a note, or something else?)

If you are saying this is already removed in v1.2, I guess just need to publish a new release since the documentation takes you to the latest release published in GitHub which is v1.1.2

**Comment by ake2l** [comment]
We actually started with the original manual and improving it step by step . For the new version 1.2.0 we reactivated the Benerator Maven Plugin and we make sure the possible options in wizard are working out of the box ( so some Benerator Wizard adjustments and archetype - adjustments as well ) ... Plus a lot other things and fixes ...

Regarding taking things out of the manual , were we can't assure these things are working flawless , ... We have to discuss this ... Maybe a beta flag can be added

**Comment by PeterBrinkhoff** [comment]
Hi @JustinH-EY , our new benerator 2.0.0 has just been released. We updated the manual as well as the wizard and made sure all remaining examples are going to work. The broken DBSnapshot has been removed. 

Would you mind rechecking and let us know if this is fine with you. 

However, the ticket may be kept open as an enhancement request for the support of the Azure SQL dialect in future releases.

**Comment by ake2l** [comment]
New dialect support has been realised in EE
